language: java

git:
quiet: false

before_install:
- brew install gradle
- gradle installWrapper
    
jobs:
include:
-jdk1: openjdk11
os1: linux
-jdk2: openjdk8
os2: osx

allow_failures:
os: osx

notifications:
email:
- s4nistri@uni-trier.de
on_success: always
on_failure: always

script: ./gradlew buildCore