language: java

git:
  quiet: false

before_install:
- brew install gradle
- gradle installWrapper
    
jobs:
  include:
  - jdk: openjdk11
    os: linux
  - jdk: openjdk8
    os: osx

  allow_failures:
  - os: osx

notifications:
  email:
  - s4nistri@uni-trier.de
  on_success: always
  on_failure: always

script: ./gradlew buildCore