name: ueb1 a3
on: 
  push:
    branches: [ main ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
        
      - name: Build with Gradle
        run: 
          ./gradlew installWrapper
          ./gradlew buildCore
